// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'qrscanner';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String ATTENDANCE = 'assets/icons/attendance.svg';
  static const String CHECKIN = 'assets/icons/checkin.svg';
  static const String CHECKOUT = 'assets/icons/checkout.svg';
  static const String HOME = 'assets/icons/home.svg';
  static const String MANAGEMENT = 'assets/icons/management.svg';
  static const String NOTIFICATION = 'assets/icons/notification.svg';
  static const String NOTIFICATIONRISE = 'assets/icons/notificationrise.svg';
  static const String PROFILE = 'assets/icons/profile.svg';
  static const String IMAGE = 'assets/image/icons/image.png';
}
